package com.hhh.study.力扣;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.IntStream;

public class 字符串查找子字符串 {

    public static void main(String[] args) {

        String string = "FAGEGEWRGAEGERSKGJIEWRHOUIQ3REGHFADJGFIUERHGIUAERFGASDKJFPQI3EHGFJPOADGAKLDNFAKNEJRHAEIRFNAJFNPEIRTIERTJAIPEROGJEAIRNRUEHGUAERIPNGFJAERNGEIPRUGHAUIGHAODNFLKADNFAKNGIERHTUERIQHTQIJGNQJRIGBNJDANFKAJDFIUQERBGQJKERGQIPREFNQPJIREGHQRUIEGBQURHTQURIPHTQUPIRNFGJQREIGNJANDGKAJHGUQIRGBNAJKLDGHUQIREBGQRHGQIREPNGQEKJRGNKQERNGFKAJGKALBFGKAERBIQUBERFQO3IRUHQIERPFNQEJIFBNALJDFBIUQEBRFAJKDSBFQIEHBFHJDSLBFJHASFUQEWBFHQGFUOQEHFHQEPGJIADBFALKDJBGQIUEUHFQJEIBFIWEHGQIBFADSGHQUIEFBQIWEBFUQIEWRHTUQIBGQIHGQUIETGHQUEBGQIHGQUEIHRQI3BFQIEWGHQUEIGHQUIHVUQIBNUQIERHUQEGNQUEIRGHQU3ITHQUEWBGQUIERHTQUEIRNQIERUTHQUITRBEWQUIJFBQIUWEGRUIQEBFQJIWEBFAKJDSBFQUIEGHRUQIOERGHOBQEJWIFNQJWEBGJBEGAKNDBGJQIEHFQIJENFAKJDFUHIQEGHU3IQRTPQHTPIEQRJNFAKJDGBAUFGHEQUIRGEQIRGHQEURIGHPQIJQWEPHFQJEWNFADKSGNQUIERHGQIREJGNIQERJGBNJKDFNAMDGBQIEROHTUIQP3RGFNIREQHQPERGFNKJDNFGAKLJDGBFNWQERQWEROUIQBEOFIJQ3BRUGBQERFJABNDKJSFBQNERFBQQWERQIOJEHFQJEFNALKWEUHRQLIUEFAGEGEWRGAEGERSKGJIEWRHOUIQ3REGHFADJGFIUERHGIUAERFGASDKJFPQI3EHGFJPOADGAKLDNFAKNEJRHAEIRFNAJFNPEIRTIERTJAIPEROGJEAIRNRUEHGUAERIPNGFJAERNGEIPRUGHAUIGHAODNFLKADNFAKNGIERHTUERIQHTQIJGNQJRIGBNJDANFKAJDFIUQERBGQJKERGQIPREFNQPJIREGHQRUIEGBQURHTQURIPHTQUPIRNFGJQREIGNJANDGKAJHGUQIRGBNAJKLDGHUQIREBGQRHGQIREPNGQEKJRGNKQERNGFKAJGKALBFGKAERBIQUBERFQO3IRUHQIERPFNQEJIFBNALJDFBIUQEBRFAJKDSBFQIEHBFHJDSLBFJHASFUQEWBFHQGFUOQEHFHQEPGJIADBFALKDJBGQIUEUHFQJEIBFIWEHGQIBFADSGHQUIEFBQIWEBFUQIEWRHTUQIBGQIHGQUIETGHQUEBGQIHGQUEIHRQI3BFQIEWGHQUEIGHQUIHVUQIBNUQIERHUQEGNQUEIRGHQU3ITHQUEWBGQUIERHTQUEIRNQIERUTHQUITRBEWQUIJFBQIUWEGRUIQEBFQJIWEBFAKJDSBFQUIEGHRUQIOERGHOBQEJWIFNQJWEBGJBEGAKNDBGJQIEHFQIJENFAKJDFUHIQEGHU3IQRTPQHTPIEQRJNFAKJDGBAUFGHEQUIRGEQIRGHQEURIGHPQIJQWEPHFQJEWNFADKSGNQUIERHGQIREJGNIQERJGBNJKDFNAMDGBQIEROHTUIQP3RGFNIREQHQPERGFNKJDNFGAKLJDGBFNWQERQWEROUIQBEOFIJQ3BRUGBQERFJABNDKJSFBQNERFBQQWERQIOJEHFQJEFNALKWEUHRQLIUEFAGEGEWRGAEGERSKGJIEWRHOUIQ3REGHFADJGFIUERHGIUAERFGASDKJFPQI3EHGFJPOADGAKLDNFAKNEJRHAEIRFNAJFNPEIRTIERTJAIPEROGJEAIRNRUEHGUAERIPNGFJAERNGEIPRUGHAUIGHAODNFLKADNFAKNGIERHTUERIQHTQIJGNQJRIGBNJDANFKAJDFIUQERBGQJKERGQIPREFNQPJIREGHQRUIEGBQURHTQURIPHTQUPIRNFGJQREIGNJANDGKAJHGUQIRGBNAJKLDGHUQIREBGQRHGQIREPNGQEKJRGNKQERNGFKAJGKALBFGKAERBIQUBERFQO3IRUHQIERPFNQEJIFBNALJDFBIUQEBRFAJKDSBFQIEHBFHJDSLBFJHASFUQEWBFHQGFUOQEHFHQEPGJIADBFALKDJBGQIUEUHFQJEIBFIWEHGQIBFADSGHQUIEFBQIWEBFUQIEWRHTUQIBGQIHGQUIETGHQUEBGQIHGQUEIHRQI3BFQIEWGHQUEIGHQUIHVUQIBNUQIERHUQEGNQUEIRGHQU3ITHQUEWBGQUIERHTQUEIRNQIERUTHQUITRBEWQUIJFBQIUWEGRUIQEBFQJIWEBFAKJDSBFQUIEGHRUQIOERGHOBQEJWIFNQJWEBGJBEGAKNDBGJQIEHFQIJENFAKJDFUHIQEGHU3IQRTPQHTPIEQRJNFAKJDGBAUFGHEQUIRGEQIRGHQEURIGHPQIJQWEPHFQJEWNFADKSGNQUIERHGQIREJGNIQERJGBNJKDFNAMDGBQIEROHTUIQP3RGFNIREQHQPERGFNKJDNFGAKLJDGBFNWQERQWEROUIQBEOFIJQ3BRUGBQERFJABNDKJSFBQNERFBQQWERQIOJEHFQJEFNALKWEUHRQLIUEFAGEGEWRGAEGERSKGJIEWRHOUIQ3REGHFADJGFIUERHGIUAERFGASDKJFPQI3EHGFJPOADGAKLDNFAKNEJRHAEIRFNAJFNPEIRTIERTJAIPEROGJEAIRNRUEHGUAERIPNGFJAERNGEIPRUGHAUIGHAODNFLKADNFAKNGIERHTUERIQHTQIJGNQJRIGBNJDANFKAJDFIUQERBGQJKERGQIPREFNQPJIREGHQRUIEGBQURHTQURIPHTQUPIRNFGJQREIGNJANDGKAJHGUQIRGBNAJKLDGHUQIREBGQRHGQIREPNGQEKJRGNKQERNGFKAJGKALBFGKAERBIQUBERFQO3IRUHQIERPFNQEJIFBNALJDFBIUQEBRFAJKDSBFQIEHBFHJDSLBFJHASFUQEWBFHQGFUOQEHFHQEPGJIADBFALKDJBGQIUEUHFQJEIBFIWEHGQIBFADSGHQUIEFBQIWEBFUQIEWRHTUQIBGQIHGQUIETGHQUEBGQIHGQUEIHRQI3BFQIEWGHQUEIGHQUIHVUQIBNUQIERHUQEGNQUEIRGHQU3ITHQUEWBGQUIERHTQUEIRNQIERUTHQUITRBEWQUIJFBQIUWEGRUIQEBFQJIWEBFAKJDSBFQUIEGHRUQIOERGHOBQEJWIFNQJWEBGJBEGAKNDBGJQIEHFQIJENFAKJDFUHIQEGHU3IQRTPQHTPIEQRJNFAKJDGBAUFGHEQUIRGEQIRGHQEURIGHPQIJQWEPHFQJEWNFADKSGNQUIERHGQIREJGNIQERJGBNJKDFNAMDGBQIEROHTUIQP3RGFNIREQHQPERGFNKJDNFGAKLJDGBFNWQERQWEROUIQBEOFIJQ3BRUGBQERFJABNDKJSFBQNERFBQQWERQIOJEHFQJEFNALKWEUHRQLIUE";
        String str = "GHQ";
        long start = System.currentTimeMillis();
        int[] search = search(string, str);
        long end = System.currentTimeMillis();
        System.out.println(Arrays.toString(search));
        System.out.println("查找时间:" + (end - start) + "毫秒");
    }


    public static int[] search(String string,String str){
        if (str.length() > string.length()){
            return null;
        }

        List<Integer> list = new ArrayList<>();
        int strCode = getCode(str, 0, str.length() - 1);
        int stringCode = getCode(string, 0, str.length() - 1);
        sign:
        for (int i = 0; i <= string.length() - str.length();i++){
            if (strCode == stringCode){
                for (int j = 0; j < str.length(); j++){
                    if (str.charAt(j) != string.charAt(i + j)){
                        continue sign;
                    }
                }
                list.add(i);
            }

            stringCode = stringCode ^ string.charAt(i) ^ string.charAt(i + str.length()-1);
        }
        int[] result = new int[list.size()];

        IntStream.range(0,result.length).forEach(i->{result[i] = list.get(i);});
        return result;
    }

    public static int getCode(String string,int beginIndex,int endIndex){
        if (beginIndex > endIndex || beginIndex < 0 || endIndex >= string.length() || string.length() <= 0){
            return 0;
        }

        int h = 0;

        for (int i = beginIndex; i <= endIndex; i++){
            h ^= string.charAt(i);
        }

        return h;

    }
}
